import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://claudex.space',
  integrations: [
    starlight({
      title: {
        en: 'Claudex',
        'zh-CN': 'Claudex',
        'zh-TW': 'Claudex',
        ja: 'Claudex',
        ko: 'Claudex',
        ru: 'Claudex',
        fr: 'Claudex',
        'pt-BR': 'Claudex',
        es: 'Claudex',
        it: 'Claudex',
        de: 'Claudex',
        pl: 'Claudex',
      },
      description: 'Multi-instance Claude Code manager with intelligent translation proxy',
      defaultLocale: 'en',
      locales: {
        en: { label: 'English' },
        'zh-cn': { label: '简体中文', lang: 'zh-CN' },
        'zh-tw': { label: '繁體中文', lang: 'zh-TW' },
        ja: { label: '日本語', lang: 'ja' },
        ko: { label: '한국어', lang: 'ko' },
        ru: { label: 'Русский', lang: 'ru' },
        fr: { label: 'Francais', lang: 'fr' },
        'pt-br': { label: 'Portugues do Brasil', lang: 'pt-BR' },
        es: { label: 'Espanol', lang: 'es' },
        it: { label: 'Italiano', lang: 'it' },
        de: { label: 'Deutsch', lang: 'de' },
        pl: { label: 'Polski', lang: 'pl' },
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/pilc80/claudex' },
        { icon: 'x.com', label: 'X', href: 'https://x.com/StringKe' },
      ],
      head: [
        // Keywords
        {
          tag: 'meta',
          attrs: { name: 'keywords', content: 'claudex, claude code, ai proxy, openai, grok, deepseek, kimi, glm, ollama, translation proxy, multi-provider' },
        },
        // OG Image
        {
          tag: 'meta',
          attrs: { property: 'og:image', content: 'https://claudex.space/og.png' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:width', content: '1200' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:height', content: '630' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:type', content: 'image/png' },
        },
        // Twitter
        {
          tag: 'meta',
          attrs: { name: 'twitter:creator', content: '@StringKe' },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:image', content: 'https://claudex.space/og.png' },
        },
        // Theme color (Discord embed accent, mobile browser address bar)
        {
          tag: 'meta',
          attrs: { name: 'theme-color', content: '#d97757' },
        },
        // Apple Touch Icon
        {
          tag: 'link',
          attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
        },
        // PNG favicons
        {
          tag: 'link',
          attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
        },
        {
          tag: 'link',
          attrs: { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' },
        },
        // JSON-LD Structured Data
        {
          tag: 'script',
          attrs: { type: 'application/ld+json' },
          content: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'SoftwareApplication',
            name: 'Claudex',
            description: 'Multi-instance Claude Code manager with intelligent translation proxy',
            url: 'https://claudex.space',
            applicationCategory: 'DeveloperApplication',
            operatingSystem: 'macOS, Linux, Windows',
            author: {
              '@type': 'Person',
              name: 'StringKe',
              url: 'https://x.com/StringKe',
            },
            offers: {
              '@type': 'Offer',
              price: '0',
              priceCurrency: 'USD',
            },
            codeRepository: 'https://github.com/pilc80/claudex',
          }),
        },
      ],
      customCss: ['./src/styles/global.css'],
      sidebar: [
        {
          label: 'Marketplace',
          translations: {
            'zh-CN': '配置集市场',
            'zh-TW': '配置集市場',
            ja: 'マーケットプレイス',
            ko: '마켓플레이스',
            ru: 'Маркетплейс',
            fr: 'Marketplace',
            'pt-BR': 'Marketplace',
            es: 'Marketplace',
            it: 'Marketplace',
            de: 'Marktplatz',
            pl: 'Marketplace',
          },
          link: '/marketplace',
        },
        {
          label: 'Getting Started',
          translations: {
            'zh-CN': '快速入门',
            'zh-TW': '快速入門',
            ja: 'はじめに',
            ko: '시작하기',
            ru: 'Начало работы',
            fr: 'Prise en main',
            'pt-BR': 'Primeiros passos',
            es: 'Primeros pasos',
            it: 'Per iniziare',
            de: 'Erste Schritte',
            pl: 'Pierwsze kroki',
          },
          items: [
            {
              slug: 'installation',
              label: 'Installation',
              translations: {
                'zh-CN': '安装',
                'zh-TW': '安裝',
                ja: 'インストール',
                ko: '설치',
                ru: 'Установка',
                fr: 'Installation',
                'pt-BR': 'Instalacao',
                es: 'Instalacion',
                it: 'Installazione',
                de: 'Installation',
                pl: 'Instalacja',
              },
            },
            {
              slug: 'configuration',
              label: 'Configuration',
              translations: {
                'zh-CN': '配置',
                'zh-TW': '設定',
                ja: '設定',
                ko: '설정',
                ru: 'Настройка',
                fr: 'Configuration',
                'pt-BR': 'Configuracao',
                es: 'Configuracion',
                it: 'Configurazione',
                de: 'Konfiguration',
                pl: 'Konfiguracja',
              },
            },
          ],
        },
        {
          label: 'Guides',
          translations: {
            'zh-CN': '使用指南',
            'zh-TW': '使用指南',
            ja: 'ガイド',
            ko: '가이드',
            ru: 'Руководства',
            fr: 'Guides',
            'pt-BR': 'Guias',
            es: 'Guias',
            it: 'Guide',
            de: 'Anleitungen',
            pl: 'Przewodniki',
          },
          items: [
            {
              slug: 'guides/provider-setup',
              label: 'Provider Setup',
              translations: {
                'zh-CN': '提供商设置',
                'zh-TW': '提供商設定',
                ja: 'プロバイダー設定',
                ko: '프로바이더 설정',
                ru: 'Настройка провайдера',
                fr: 'Configuration du fournisseur',
                'pt-BR': 'Configuracao do provedor',
                es: 'Configuracion del proveedor',
                it: 'Configurazione del provider',
                de: 'Anbieter einrichten',
                pl: 'Konfiguracja dostawcy',
              },
            },
          ],
        },
        {
          label: 'Features',
          translations: {
            'zh-CN': '功能特性',
            'zh-TW': '功能特性',
            ja: '機能',
            ko: '기능',
            ru: 'Возможности',
            fr: 'Fonctionnalites',
            'pt-BR': 'Funcionalidades',
            es: 'Funcionalidades',
            it: 'Funzionalita',
            de: 'Funktionen',
            pl: 'Funkcje',
          },
          items: [
            {
              slug: 'features/translation-proxy',
              label: 'Translation Proxy',
              translations: {
                'zh-CN': '翻译代理',
                'zh-TW': '翻譯代理',
                ja: '翻訳プロキシ',
                ko: '번역 프록시',
                ru: 'Прокси-переводчик',
                fr: 'Proxy de traduction',
                'pt-BR': 'Proxy de traducao',
                es: 'Proxy de traduccion',
                it: 'Proxy di traduzione',
                de: 'Ubersetzungsproxy',
                pl: 'Proxy tlumaczenia',
              },
            },
            {
              slug: 'features/circuit-breaker',
              label: 'Circuit Breaker',
              translations: {
                'zh-CN': '断路器',
                'zh-TW': '斷路器',
                ja: 'サーキットブレーカー',
                ko: '서킷 브레이커',
                ru: 'Автоматический выключатель',
                fr: 'Disjoncteur',
                'pt-BR': 'Disjuntor',
                es: 'Cortacircuitos',
                it: 'Interruttore automatico',
                de: 'Sicherungsautomat',
                pl: 'Wylacznik automatyczny',
              },
            },
            {
              slug: 'features/smart-routing',
              label: 'Smart Routing',
              translations: {
                'zh-CN': '智能路由',
                'zh-TW': '智能路由',
                ja: 'スマートルーティング',
                ko: '스마트 라우팅',
                ru: 'Умная маршрутизация',
                fr: 'Routage intelligent',
                'pt-BR': 'Roteamento inteligente',
                es: 'Enrutamiento inteligente',
                it: 'Routing intelligente',
                de: 'Intelligentes Routing',
                pl: 'Inteligentny routing',
              },
            },
            {
              slug: 'features/context-engine',
              label: 'Context Engine',
              translations: {
                'zh-CN': '上下文引擎',
                'zh-TW': '上下文引擎',
                ja: 'コンテキストエンジン',
                ko: '컨텍스트 엔진',
                ru: 'Контекстный движок',
                fr: 'Moteur de contexte',
                'pt-BR': 'Motor de contexto',
                es: 'Motor de contexto',
                it: 'Motore di contesto',
                de: 'Kontextmaschine',
                pl: 'Silnik kontekstu',
              },
            },
            {
              slug: 'features/tui-dashboard',
              label: 'TUI Dashboard',
              translations: {
                'zh-CN': 'TUI 仪表盘',
                'zh-TW': 'TUI 儀表板',
                ja: 'TUI ダッシュボード',
                ko: 'TUI 대시보드',
                ru: 'TUI панель',
                fr: 'Tableau de bord TUI',
                'pt-BR': 'Painel TUI',
                es: 'Panel TUI',
                it: 'Pannello TUI',
                de: 'TUI-Dashboard',
                pl: 'Panel TUI',
              },
            },
            {
              slug: 'features/self-update',
              label: 'Self Update',
              translations: {
                'zh-CN': '自动更新',
                'zh-TW': '自動更新',
                ja: '自動更新',
                ko: '자동 업데이트',
                ru: 'Самообновление',
                fr: 'Mise a jour automatique',
                'pt-BR': 'Atualizacao automatica',
                es: 'Actualizacion automatica',
                it: 'Aggiornamento automatico',
                de: 'Automatisches Update',
                pl: 'Automatyczna aktualizacja',
              },
            },
            {
              slug: 'features/oauth-subscriptions',
              label: 'OAuth Subscriptions',
              translations: {
                'zh-CN': 'OAuth 订阅认证',
                'zh-TW': 'OAuth 訂閱認證',
                ja: 'OAuth サブスクリプション',
                ko: 'OAuth 구독 인증',
                ru: 'OAuth подписки',
                fr: 'Abonnements OAuth',
                'pt-BR': 'Assinaturas OAuth',
                es: 'Suscripciones OAuth',
                it: 'Abbonamenti OAuth',
                de: 'OAuth-Abonnements',
                pl: 'Subskrypcje OAuth',
              },
            },
            {
              slug: 'features/configuration-sets',
              label: 'Configuration Sets',
              translations: {
                'zh-CN': '配置集',
                'zh-TW': '配置集',
                ja: '構成セット',
                ko: '구성 세트',
                ru: 'Наборы конфигурации',
                fr: 'Jeux de configuration',
                'pt-BR': 'Conjuntos de configuracao',
                es: 'Conjuntos de configuracion',
                it: 'Set di configurazione',
                de: 'Konfigurationspakete',
                pl: 'Zestawy konfiguracji',
              },
            },
            {
              slug: 'features/terminal-hyperlinks',
              label: 'Terminal Hyperlinks',
              translations: {
                'zh-CN': '终端超链接',
                'zh-TW': '終端超連結',
                ja: 'ターミナルハイパーリンク',
                ko: '터미널 하이퍼링크',
                ru: 'Гиперссылки терминала',
                fr: 'Hyperliens du terminal',
                'pt-BR': 'Hyperlinks do terminal',
                es: 'Hipervinculos de terminal',
                it: 'Hyperlink del terminale',
                de: 'Terminal-Hyperlinks',
                pl: 'Hiperlinki terminala',
              },
            },
            {
              slug: 'features/model-slot-mapping',
              label: 'Model Slot Mapping',
              translations: {
                'zh-CN': '模型槽位映射',
                'zh-TW': '模型槽位映射',
                ja: 'モデルスロットマッピング',
                ko: '모델 슬롯 매핑',
                ru: 'Маппинг слотов моделей',
                fr: 'Mappage des slots de modeles',
                'pt-BR': 'Mapeamento de slots de modelo',
                es: 'Mapeo de slots de modelo',
                it: 'Mappatura slot modello',
                de: 'Modell-Slot-Zuordnung',
                pl: 'Mapowanie slotow modeli',
              },
            },
          ],
        },
        {
          label: 'Reference',
          translations: {
            'zh-CN': '参考',
            'zh-TW': '參考',
            ja: 'リファレンス',
            ko: '레퍼런스',
            ru: 'Справочник',
            fr: 'Reference',
            'pt-BR': 'Referencia',
            es: 'Referencia',
            it: 'Riferimento',
            de: 'Referenz',
            pl: 'Dokumentacja',
          },
          items: [
            {
              slug: 'reference/cli',
              label: 'CLI Reference',
              translations: {
                'zh-CN': 'CLI 参考',
                'zh-TW': 'CLI 參考',
                ja: 'CLI リファレンス',
                ko: 'CLI 레퍼런스',
                ru: 'Справочник CLI',
                fr: 'Reference CLI',
                'pt-BR': 'Referencia CLI',
                es: 'Referencia CLI',
                it: 'Riferimento CLI',
                de: 'CLI-Referenz',
                pl: 'Dokumentacja CLI',
              },
            },
            {
              slug: 'reference/config',
              label: 'Config Reference',
              translations: {
                'zh-CN': '配置参考',
                'zh-TW': '設定參考',
                ja: '設定リファレンス',
                ko: '설정 레퍼런스',
                ru: 'Справочник настроек',
                fr: 'Reference de configuration',
                'pt-BR': 'Referencia de configuracao',
                es: 'Referencia de configuracion',
                it: 'Riferimento configurazione',
                de: 'Konfigurationsreferenz',
                pl: 'Dokumentacja konfiguracji',
              },
            },
            {
              slug: 'reference/providers',
              label: 'Provider Compatibility',
              translations: {
                'zh-CN': 'Provider 兼容表',
                'zh-TW': 'Provider 相容表',
                ja: 'プロバイダー互換性',
                ko: '프로바이더 호환성',
                ru: 'Совместимость провайдеров',
                fr: 'Compatibilite des fournisseurs',
                'pt-BR': 'Compatibilidade de provedores',
                es: 'Compatibilidad de proveedores',
                it: 'Compatibilita dei provider',
                de: 'Anbieterkompatibilitat',
                pl: 'Kompatybilnosc dostawcow',
              },
            },
          ],
        },
      ],
    }),
    sitemap(),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
